cargo-features = ["strip"]

[workspace]
members = [
    "alacritty",
    "alacritty_terminal",
    "alacritty_config_derive",
]

[profile.release]
lto = "thin"
codegen-units = 1
panic = "abort"
strip = "symbols"
