[workspace]
members = [
    "alacritty",
    "alacritty_terminal",
    "font",
]

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"

[patch.crates-io]
servo-freetype-sys = { path = "servo-freetype-proxy" }
